<?php
/**
 * Created by PhpStorm.
 * User: MinngYue
 * Date: 2020/1/6
 * Time: 16:18
 */
namespace app\modules\homing;

class HomingModule extends \yii\base\Module
{
    /**
     * @var string
     */
    public $controllerNamespace = 'app\modules\home\controllers';

    /**
     * Author Minnyue
     * Created At 2020/1/6 16:21
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (\Yii::$app instanceof \yii\console\Application){
            $this->controllerNamespace = 'app\modules\home\commands';
        }
        \Yii::configure($this,require __DIR__ . '/config.php');
    }
}