<?php


namespace app\controllers\restful;

use Yii;
use app\models\User;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\ActiveController;

class UserController extends ActiveController
{
    public $layout = false;
    public $modelClass = 'app\models\User';     //通过指定 modelClass 作为 app\models\User，控制器就能知道使用哪个模型去获取和处理数据。


    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
//        $behaviors['authenticator'] = [
//            'class' => HttpBasicAuth::className(),
//        ];
        return $behaviors;

    }

    public function actionView($id)
    {
        return User::findOne($id);
    }
}