<?php
/**
 * 封装通用方法
 * User: MinngYue
 * Date: 2019/12/27
 * Time: 17:18
 */
namespace app\components\models;

use yii\db\ActiveRecord;

class UModel extends ActiveRecord
{
    static function findOne($condition)
    {
        return parent::findOne($condition); // TODO: Change the autogenerated stub
    }

    static function findAll($condition)
    {
        return parent::findAll($condition); // TODO: Change the autogenerated stub
    }

    static function findBySql($sql, $params = [])
    {
        return parent::findBySql($sql, $params); // TODO: Change the autogenerated stub
    }

    static function findByCondition($condition)
    {
        return parent::findByCondition($condition); // TODO: Change the autogenerated stub
    }
}