<?php
/**
 * Created by PhpStorm.
 * User: MinngYue
 * Date: 2020/3/10
 * Time: 14:32
 */
namespace app\modules\vuecms;

class VuecmsModule extends \yii\base\Module
{
    /**
     * @var string
     */
    public $controllerNamespace = 'app\modules\vuecms\controllers';

    /**
     * Author Minnyue
     * Created At 2020/3/10 14:33
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (\Yii::$app instanceof \yii\console\Application){
            $this->controllerNamespace = 'app\modules\vuecms\commands';
        }

    }
}