<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property int $id
 * @property string $email 登录邮箱
 * @property string $name 昵称
 * @property string $password_hash 密码
 * @property string $auth_key
 * @property int $type 用户类型，10:普通用户 20:管理员
 * @property int $status 会员状态
 * @property string $ip 注册ip
 * @property string $location IP地址
 * @property string|null $created_at 创建时间
 * @property string|null $updated_at 更新时间
 */
class User extends \app\components\models\UBModel implements IdentityInterface
{
    /**
 * {@inheritdoc}
 */
    public static function tableName()
    {
        return '{{%user}}';
    }

    public function profile(){
        return $this->hasOne(Profile::className(),['id'=>'user_id']);
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['auth_key', 'status'], 'required'],
            [['type', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['email', 'name'], 'string', 'max' => 50],
            [['password_hash', 'auth_key', 'ip'], 'string', 'max' => 250],
            [['location'], 'string', 'max' => 255],
            [['email'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'name' => 'Name',
            'password_hash' => 'Password Hash',
            'auth_key' => 'Auth Key',
            'type' => 'Type',
            'status' => 'Status',
            'ip' => 'Ip',
            'location' => 'Location',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public static function findIdentity($id)
    {
        if (file_exists(Yii::getAlias("@runtime") . '/install/install.lock')){
            return static::findOne(['id'=>$id,'status'=>self::ACTION_STATUS]);
        }
        return null;
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not  implemented.');
    }

    public function getId()
    {
        return $this->getPrimaryKey();
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }
    /**
     * @param string $password
     * @param string $cost
     */
    public function setPassword($password,$cost = null){
        $this->password_hash = Yii::$app->security->generatePasswordHash($password,$cost);
    }

    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    public function fields()
    {
//        $fields = parent::fields();
//        // 删除一些包含敏感信息的字段
//        unset($fields['auth_key'], $fields['password_hash'], $fields['password_reset_token']);
//
//        return $fields;


        return [
            'id',
            'email',
            'name'=>function($model){
                return $model->first_name.' '.$model->last_name;
            },
            'location'
        ];
    }

    public function extraFields()
    {
//        return parent::extraFields(); // TODO: Change the autogenerated stub
        return ['profile'];
    }
}
